<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>6 Week 5 | Untitled</title>
  <meta name="description" content="6 Week 5 | Untitled" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="6 Week 5 | Untitled" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="6 Week 5 | Untitled" />
  
  
  

<meta name="author" content="Steminist_R lessons edited by Serena Caplins" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="week-4.html"/>
<link rel="next" href="week-6-pca.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Marine Genomics 2021</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction to Marine Genomics</a></li>
<li class="chapter" data-level="2" data-path="week-1.html"><a href="week-1.html"><i class="fa fa-check"></i><b>2</b> Week 1</a>
<ul>
<li class="chapter" data-level="2.1" data-path="week-1.html"><a href="week-1.html#introduction-to-shell-computing-via-the-data-carpentry-tutorial"><i class="fa fa-check"></i><b>2.1</b> Introduction to shell computing via the data carpentry tutorial</a></li>
<li class="chapter" data-level="2.2" data-path="week-1.html"><a href="week-1.html#how-to-access-the-shell"><i class="fa fa-check"></i><b>2.2</b> How to access the shell</a></li>
<li class="chapter" data-level="2.3" data-path="week-1.html"><a href="week-1.html#navigating-your-file-system"><i class="fa fa-check"></i><b>2.3</b> Navigating your file system</a></li>
<li class="chapter" data-level="2.4" data-path="week-1.html"><a href="week-1.html#shortcut-tab-completion"><i class="fa fa-check"></i><b>2.4</b> Shortcut: Tab Completion</a></li>
<li class="chapter" data-level="2.5" data-path="week-1.html"><a href="week-1.html#summary-key-points"><i class="fa fa-check"></i><b>2.5</b> Summary &amp; Key Points</a></li>
<li class="chapter" data-level="2.6" data-path="week-1.html"><a href="week-1.html#navigating-files-and-directories"><i class="fa fa-check"></i><b>2.6</b> Navigating Files and Directories</a></li>
<li class="chapter" data-level="2.7" data-path="week-1.html"><a href="week-1.html#week-1-objectives"><i class="fa fa-check"></i><b>2.7</b> Week 1 Objectives</a></li>
<li class="chapter" data-level="2.8" data-path="week-1.html"><a href="week-1.html#moving-around-the-file-system"><i class="fa fa-check"></i><b>2.8</b> Moving around the file system</a></li>
<li class="chapter" data-level="2.9" data-path="week-1.html"><a href="week-1.html#examining-the-contents-of-other-directories"><i class="fa fa-check"></i><b>2.9</b> Examining the contents of other directories</a></li>
<li class="chapter" data-level="2.10" data-path="week-1.html"><a href="week-1.html#full-vs-relative-paths"><i class="fa fa-check"></i><b>2.10</b> Full vs Relative Paths</a></li>
<li class="chapter" data-level="2.11" data-path="week-1.html"><a href="week-1.html#navigational-shortcuts"><i class="fa fa-check"></i><b>2.11</b> Navigational shortcuts</a></li>
<li class="chapter" data-level="2.12" data-path="week-1.html"><a href="week-1.html#key-points"><i class="fa fa-check"></i><b>2.12</b> Key Points</a></li>
<li class="chapter" data-level="2.13" data-path="week-1.html"><a href="week-1.html#creature-of-the-week"><i class="fa fa-check"></i><b>2.13</b> Creature of the Week!</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-2.html"><a href="week-2.html"><i class="fa fa-check"></i><b>3</b> Week 2</a>
<ul>
<li class="chapter" data-level="3.1" data-path="week-2.html"><a href="week-2.html#working-with-files"><i class="fa fa-check"></i><b>3.1</b> Working With Files</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="week-2.html"><a href="week-2.html#our-data-set-fastq-files"><i class="fa fa-check"></i><b>3.1.1</b> Our data set: FASTQ files</a></li>
<li class="chapter" data-level="3.1.2" data-path="week-2.html"><a href="week-2.html#wildcards"><i class="fa fa-check"></i><b>3.1.2</b> Wildcards</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="week-2.html"><a href="week-2.html#command-history"><i class="fa fa-check"></i><b>3.2</b> Command History</a></li>
<li class="chapter" data-level="3.3" data-path="week-2.html"><a href="week-2.html#examining-files"><i class="fa fa-check"></i><b>3.3</b> Examining Files</a></li>
<li class="chapter" data-level="3.4" data-path="week-2.html"><a href="week-2.html#details-on-the-fastq-format"><i class="fa fa-check"></i><b>3.4</b> Details on the FASTQ format</a></li>
<li class="chapter" data-level="3.5" data-path="week-2.html"><a href="week-2.html#creating-moving-copying-and-removing"><i class="fa fa-check"></i><b>3.5</b> Creating, moving, copying, and removing</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="week-2.html"><a href="week-2.html#copying-files"><i class="fa fa-check"></i><b>3.5.1</b> Copying Files</a></li>
<li class="chapter" data-level="3.5.2" data-path="week-2.html"><a href="week-2.html#creating-directories"><i class="fa fa-check"></i><b>3.5.2</b> Creating Directories</a></li>
<li class="chapter" data-level="3.5.3" data-path="week-2.html"><a href="week-2.html#moving-renaming"><i class="fa fa-check"></i><b>3.5.3</b> Moving / Renaming</a></li>
<li class="chapter" data-level="3.5.4" data-path="week-2.html"><a href="week-2.html#file-permissions"><i class="fa fa-check"></i><b>3.5.4</b> File Permissions</a></li>
<li class="chapter" data-level="3.5.5" data-path="week-2.html"><a href="week-2.html#removing"><i class="fa fa-check"></i><b>3.5.5</b> Removing</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="week-2.html"><a href="week-2.html#redirections"><i class="fa fa-check"></i><b>3.6</b> Redirections</a></li>
<li class="chapter" data-level="3.7" data-path="week-2.html"><a href="week-2.html#searching-files"><i class="fa fa-check"></i><b>3.7</b> Searching files</a></li>
<li class="chapter" data-level="3.8" data-path="week-2.html"><a href="week-2.html#redirecting-output"><i class="fa fa-check"></i><b>3.8</b> Redirecting output</a></li>
<li class="chapter" data-level="3.9" data-path="week-2.html"><a href="week-2.html#writing-for-loops"><i class="fa fa-check"></i><b>3.9</b> Writing for loops</a></li>
<li class="chapter" data-level="3.10" data-path="week-2.html"><a href="week-2.html#using-basename-in-for-loops"><i class="fa fa-check"></i><b>3.10</b> Using Basename in for loops</a></li>
<li class="chapter" data-level="3.11" data-path="week-2.html"><a href="week-2.html#writing-scripts-and-working-with-data"><i class="fa fa-check"></i><b>3.11</b> Writing Scripts and Working with Data</a></li>
<li class="chapter" data-level="3.12" data-path="week-2.html"><a href="week-2.html#writing-files"><i class="fa fa-check"></i><b>3.12</b> Writing files</a></li>
<li class="chapter" data-level="3.13" data-path="week-2.html"><a href="week-2.html#writing-scripts"><i class="fa fa-check"></i><b>3.13</b> Writing scripts</a></li>
<li class="chapter" data-level="3.14" data-path="week-2.html"><a href="week-2.html#moving-and-downloading-data"><i class="fa fa-check"></i><b>3.14</b> Moving and Downloading Data</a>
<ul>
<li class="chapter" data-level="3.14.1" data-path="week-2.html"><a href="week-2.html#getting-data-from-the-cloud"><i class="fa fa-check"></i><b>3.14.1</b> Getting data from the cloud</a></li>
<li class="chapter" data-level="3.14.2" data-path="week-2.html"><a href="week-2.html#uploading-and-downloading-data-to-your-virtual-machine-with-scp---unix"><i class="fa fa-check"></i><b>3.14.2</b> Uploading and Downloading Data to your Virtual Machine with scp - UNIX</a></li>
</ul></li>
<li class="chapter" data-level="3.15" data-path="week-2.html"><a href="week-2.html#awk"><i class="fa fa-check"></i><b>3.15</b> Awk</a></li>
<li class="chapter" data-level="3.16" data-path="week-2.html"><a href="week-2.html#creature-of-the-week-1"><i class="fa fa-check"></i><b>3.16</b> Creature of the Week!</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-3.html"><a href="week-3.html"><i class="fa fa-check"></i><b>4</b> Week 3</a>
<ul>
<li class="chapter" data-level="4.1" data-path="week-3.html"><a href="week-3.html#what-is-a-genetic-variant"><i class="fa fa-check"></i><b>4.1</b> What is a Genetic Variant?</a></li>
<li class="chapter" data-level="4.2" data-path="week-3.html"><a href="week-3.html#to-get-started-lets-dowload-the-data-and-install-a-few-programs"><i class="fa fa-check"></i><b>4.2</b> To get started lets dowload the data and install a few programs</a></li>
<li class="chapter" data-level="4.3" data-path="week-3.html"><a href="week-3.html#raw-read-quality-control"><i class="fa fa-check"></i><b>4.3</b> Raw read quality control</a></li>
<li class="chapter" data-level="4.4" data-path="week-3.html"><a href="week-3.html#trimming-to-remove-adapters"><i class="fa fa-check"></i><b>4.4</b> Trimming to remove adapters</a></li>
<li class="chapter" data-level="4.5" data-path="week-3.html"><a href="week-3.html#building-an-index-of-our-genome"><i class="fa fa-check"></i><b>4.5</b> Building an index of our genome</a></li>
<li class="chapter" data-level="4.6" data-path="week-3.html"><a href="week-3.html#map-reads-to-the-genome"><i class="fa fa-check"></i><b>4.6</b> Map reads to the genome</a></li>
<li class="chapter" data-level="4.7" data-path="week-3.html"><a href="week-3.html#sam-to-bam-file-conversion"><i class="fa fa-check"></i><b>4.7</b> sam to bam file conversion</a></li>
<li class="chapter" data-level="4.8" data-path="week-3.html"><a href="week-3.html#genotype-likelihoods"><i class="fa fa-check"></i><b>4.8</b> Genotype likelihoods</a></li>
<li class="chapter" data-level="4.9" data-path="week-3.html"><a href="week-3.html#creature-of-the-week-2"><i class="fa fa-check"></i><b>4.9</b> Creature of the Week!</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="week-4.html"><a href="week-4.html"><i class="fa fa-check"></i><b>5</b> Week 4</a>
<ul>
<li class="chapter" data-level="5.1" data-path="week-4.html"><a href="week-4.html#lesson-1-orientation-to-r"><i class="fa fa-check"></i><b>5.1</b> Lesson 1: Orientation to R</a></li>
<li class="chapter" data-level="5.2" data-path="week-4.html"><a href="week-4.html#manipulating-a-vector-object"><i class="fa fa-check"></i><b>5.2</b> Manipulating a vector object</a></li>
<li class="chapter" data-level="5.3" data-path="week-4.html"><a href="week-4.html#operations-act-on-each-element-of-a-vector"><i class="fa fa-check"></i><b>5.3</b> Operations act on each element of a vector:</a></li>
<li class="chapter" data-level="5.4" data-path="week-4.html"><a href="week-4.html#operations-can-also-work-with-two-vectors"><i class="fa fa-check"></i><b>5.4</b> Operations can also work with two vectors:</a></li>
<li class="chapter" data-level="5.5" data-path="week-4.html"><a href="week-4.html#a-few-tips-below-for-working-with-objects"><i class="fa fa-check"></i><b>5.5</b> A few tips below for working with objects:</a></li>
<li class="chapter" data-level="5.6" data-path="week-4.html"><a href="week-4.html#practice-r-operations"><i class="fa fa-check"></i><b>5.6</b> Practice R Operations</a></li>
<li class="chapter" data-level="5.7" data-path="week-4.html"><a href="week-4.html#characterizing-a-dataframe"><i class="fa fa-check"></i><b>5.7</b> 1.2 Characterizing a dataframe</a></li>
<li class="chapter" data-level="5.8" data-path="week-4.html"><a href="week-4.html#how-to-access-parts-of-the-data"><i class="fa fa-check"></i><b>5.8</b> How to access parts of the data:</a></li>
<li class="chapter" data-level="5.9" data-path="week-4.html"><a href="week-4.html#data-manipulation"><i class="fa fa-check"></i><b>5.9</b> Data Manipulation</a></li>
<li class="chapter" data-level="5.10" data-path="week-4.html"><a href="week-4.html#practice-exploring-a-dataframe"><i class="fa fa-check"></i><b>5.10</b> Practice exploring a dataframe</a></li>
<li class="chapter" data-level="5.11" data-path="week-4.html"><a href="week-4.html#subsetting-datasets-logicals"><i class="fa fa-check"></i><b>5.11</b> 1.3 Subsetting datasets &amp; logicals</a></li>
<li class="chapter" data-level="5.12" data-path="week-4.html"><a href="week-4.html#practice-subsetting-datasetslogicals"><i class="fa fa-check"></i><b>5.12</b> Practice Subsetting datasets/logicals</a></li>
<li class="chapter" data-level="5.13" data-path="week-4.html"><a href="week-4.html#creature-of-the-week-3"><i class="fa fa-check"></i><b>5.13</b> Creature of the Week!</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="week-5.html"><a href="week-5.html"><i class="fa fa-check"></i><b>6</b> Week 5</a>
<ul>
<li class="chapter" data-level="6.1" data-path="week-5.html"><a href="week-5.html#plotting"><i class="fa fa-check"></i><b>6.1</b> 2.1 Plotting</a></li>
<li class="chapter" data-level="6.2" data-path="week-5.html"><a href="week-5.html#scatterplots"><i class="fa fa-check"></i><b>6.2</b> Scatterplots</a></li>
<li class="chapter" data-level="6.3" data-path="week-5.html"><a href="week-5.html#customizing-your-plot"><i class="fa fa-check"></i><b>6.3</b> Customizing your plot</a></li>
<li class="chapter" data-level="6.4" data-path="week-5.html"><a href="week-5.html#practice-problems-2.1"><i class="fa fa-check"></i><b>6.4</b> Practice Problems 2.1</a></li>
<li class="chapter" data-level="6.5" data-path="week-5.html"><a href="week-5.html#plotting-with-ggplot2"><i class="fa fa-check"></i><b>6.5</b> 2.2 plotting with ggplot2</a></li>
<li class="chapter" data-level="6.6" data-path="week-5.html"><a href="week-5.html#practice-problems-2.2"><i class="fa fa-check"></i><b>6.6</b> Practice Problems 2.2</a></li>
<li class="chapter" data-level="6.7" data-path="week-5.html"><a href="week-5.html#for-loops-and-the-apply-family-of-functions"><i class="fa fa-check"></i><b>6.7</b> For loops and the apply family of functions</a></li>
<li class="chapter" data-level="6.8" data-path="week-5.html"><a href="week-5.html#apply-family"><i class="fa fa-check"></i><b>6.8</b> apply family</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="week-5.html"><a href="week-5.html#sapply"><i class="fa fa-check"></i><b>6.8.1</b> sapply</a></li>
<li class="chapter" data-level="6.8.2" data-path="week-5.html"><a href="week-5.html#apply"><i class="fa fa-check"></i><b>6.8.2</b> apply</a></li>
<li class="chapter" data-level="6.8.3" data-path="week-5.html"><a href="week-5.html#lapply-list-apply"><i class="fa fa-check"></i><b>6.8.3</b> lapply – “list” apply</a></li>
<li class="chapter" data-level="6.8.4" data-path="week-5.html"><a href="week-5.html#tapply---per-type-apply"><i class="fa fa-check"></i><b>6.8.4</b> tapply - “per Type” apply</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="week-5.html"><a href="week-5.html#exercise-2.3-apply-and-tapply"><i class="fa fa-check"></i><b>6.9</b> Exercise 2.3 apply and tapply</a></li>
<li class="chapter" data-level="6.10" data-path="week-5.html"><a href="week-5.html#creature-of-the-week-4"><i class="fa fa-check"></i><b>6.10</b> Creature of the Week!</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="week-6-pca.html"><a href="week-6-pca.html"><i class="fa fa-check"></i><b>7</b> Week 6: PCA</a>
<ul>
<li class="chapter" data-level="7.1" data-path="week-6-pca.html"><a href="week-6-pca.html#download-the-data"><i class="fa fa-check"></i><b>7.1</b> Download the data</a></li>
<li class="chapter" data-level="7.2" data-path="week-6-pca.html"><a href="week-6-pca.html#installing-programs"><i class="fa fa-check"></i><b>7.2</b> Installing programs</a></li>
<li class="chapter" data-level="7.3" data-path="week-6-pca.html"><a href="week-6-pca.html#run-pcangsd-on-our-data"><i class="fa fa-check"></i><b>7.3</b> Run pcangsd on our data</a></li>
<li class="chapter" data-level="7.4" data-path="week-6-pca.html"><a href="week-6-pca.html#setting-up-a-new-project-in-r"><i class="fa fa-check"></i><b>7.4</b> Setting up a new project in R</a></li>
<li class="chapter" data-level="7.5" data-path="week-6-pca.html"><a href="week-6-pca.html#reading-data-into-r"><i class="fa fa-check"></i><b>7.5</b> Reading data into R</a></li>
<li class="chapter" data-level="7.6" data-path="week-6-pca.html"><a href="week-6-pca.html#exercises"><i class="fa fa-check"></i><b>7.6</b> Exercises</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Untitled</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="week-5" class="section level1" number="6">
<h1><span class="header-section-number">6</span> Week 5</h1>
<p>We’re again drawing some of this material from the STEMinist_R materials which can be found <a href="https://github.com/ecalfee/STEMinist_R.git">here</a></p>
<div id="plotting" class="section level2" number="6.1">
<h2><span class="header-section-number">6.1</span> 2.1 Plotting</h2>
<p>These lessons are evenly divided between live coding and performed by the instructor and exercises performed by the students in class with instructor support.</p>
<p>This class will take place with students typing directly into an R script for the exercises all of which can be found in the Week 4 file <a href="https://github.com/BayLab/MarineGenomicsData.git">here</a></p>
<p>You can download just the R files for just this week via wget with the following link</p>
<pre class="{html"><code>wget https://raw.githubusercontent.com/BayLab/MarineGenomicsData/main/week5.tar.gz</code></pre>
<p>this is a compressed file which can be uncompressed via:</p>
<pre><code>tar -xzvf week5.tar.gz</code></pre>
<ul>
<li>A few useful commands that we will cover include:
<ul>
<li>points()</li>
<li>lines()</li>
<li>abline()</li>
<li>hist()</li>
<li>boxplot()</li>
<li>plot()
<ul>
<li>A few useful arguments within plot(): main, xlab, ylab, col, pch, cex</li>
</ul></li>
</ul></li>
</ul>
</div>
<div id="scatterplots" class="section level2" number="6.2">
<h2><span class="header-section-number">6.2</span> Scatterplots</h2>
<p>Within our <code>msleep</code> dataframe let’s plot sleep_total by bodywt (bodyweight)</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="week-5.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-2"><a href="week-5.html#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(msleep)</span>
<span id="cb3-3"><a href="week-5.html#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="week-5.html#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(msleep<span class="sc">$</span>sleep_total,msleep<span class="sc">$</span>sleep_rem)</span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="week-5.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># or plot response variable as a function &quot;~&quot; of the predictor variable</span></span>
<span id="cb4-2"><a href="week-5.html#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="week-5.html#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(msleep<span class="sc">$</span>sleep_total<span class="sc">~</span>msleep<span class="sc">$</span>sleep_rem) <span class="co">#you&#39;ll notice this swaps the x and y axis</span></span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-1-2.png" width="672" /></p>
</div>
<div id="customizing-your-plot" class="section level2" number="6.3">
<h2><span class="header-section-number">6.3</span> Customizing your plot</h2>
<ul>
<li>There are several different arguments within plotting functions that can be used to customize your plot.
<ul>
<li><code>col</code> changes color</li>
<li><code>pch</code> changes point character</li>
<li><code>cex</code> changes size</li>
<li><code>type</code> changes type (“l” = line, “p” = points, “b” = both)</li>
<li><code>lty</code> changes line type</li>
<li><code>bty</code> changes (or removes) the border around the plot (“n” = no box, “7” = top + right, “L” = bottom+left, “C” top+left+bottom, “U” = left+bottom+right)</li>
</ul></li>
</ul>
<p>You can view different point characters with <code>?pch</code></p>
<p>There are <strong>many</strong> color options in R. For some general colors you can write the name (blue, red, green, etc). There are apparently 657 named colors in R (including "slateblue3, and peachpuff4) but you can also use the color hexidecimal code for a given color. There are several comprehensives guides for colors in R online and one of which can be found (here)[<a href="https://www.nceas.ucsb.edu/sites/default/files/2020-04/colorPaletteCheatsheet.pdf" class="uri">https://www.nceas.ucsb.edu/sites/default/files/2020-04/colorPaletteCheatsheet.pdf</a>]</p>
<p>Let’s remake the total_sleep against sleep_rem plot and add-in some modifiers</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="week-5.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Choose a pch and make the color blue and give it a bottom+left border</span></span>
<span id="cb5-2"><a href="week-5.html#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(msleep<span class="sc">$</span>sleep_total<span class="sc">~</span>msleep<span class="sc">$</span>sleep_rem, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>, <span class="at">bty=</span><span class="st">&quot;L&quot;</span>)</span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>We can change the axes and title labels using “xlab,” “ylab,” and “main” arguments. Let’s add labels to our plot.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="week-5.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Choose a pch and make the color blue and give it a bottom+left border</span></span>
<span id="cb6-2"><a href="week-5.html#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(msleep<span class="sc">$</span>sleep_total<span class="sc">~</span>msleep<span class="sc">$</span>sleep_rem, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>, <span class="at">bty=</span><span class="st">&quot;L&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;REM Sleep (hours)&quot;</span>, <span class="at">ylab=</span> <span class="st">&quot;Total Sleep (hours)&quot;</span>) </span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>You may want to find out which points are on a plot. You can use <code>identify()</code> in place of <code>plot()</code> to identify specific points within your plot. This function prints out the row numbers for the points that you selected.</p>
<p>We can also add lines to an existing plot with <code>ablines()</code>. Let’s add a line fit from a linear model to our plot.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="week-5.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#first make a plot</span></span>
<span id="cb7-2"><a href="week-5.html#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(msleep<span class="sc">$</span>sleep_total<span class="sc">~</span>msleep<span class="sc">$</span>sleep_rem, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>, <span class="at">bty=</span><span class="st">&quot;L&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;REM Sleep (hours)&quot;</span>, <span class="at">ylab=</span> <span class="st">&quot;Total Sleep (hours)&quot;</span>) </span>
<span id="cb7-3"><a href="week-5.html#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="week-5.html#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">#then add a line. The function lm runs a linear model on our x, y values.</span></span>
<span id="cb7-5"><a href="week-5.html#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(msleep<span class="sc">$</span>sleep_total<span class="sc">~</span>msleep<span class="sc">$</span>sleep_rem))</span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>You can add a legend to a plot with <code>legend()</code> which needs you to specify the location.</p>
<p>To do this, let’s make a cutoff for our points and color them by points above and below the cutoff. We’ll use our subsetting skills from last week. Feel free to review that section (1.3).</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="week-5.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#start by defining points by whether they are greater than sleep_total 16 and storing</span></span>
<span id="cb8-2"><a href="week-5.html#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co">#first make a empty column named colors within the msleep dataframe</span></span>
<span id="cb8-3"><a href="week-5.html#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="week-5.html#cb8-4" aria-hidden="true" tabindex="-1"></a>msleep<span class="sc">$</span>colors<span class="ot">=</span><span class="cn">NA</span></span>
<span id="cb8-5"><a href="week-5.html#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co">#store the colors &quot;red&quot; or &quot;black&quot; in the color column for the rows that satsify the following criteria.</span></span>
<span id="cb8-6"><a href="week-5.html#cb8-6" aria-hidden="true" tabindex="-1"></a>msleep<span class="sc">$</span>colors[msleep<span class="sc">$</span>sleep_total <span class="sc">&gt;=</span> <span class="dv">17</span>] <span class="ot">&lt;-</span><span class="st">&quot;red&quot;</span></span>
<span id="cb8-7"><a href="week-5.html#cb8-7" aria-hidden="true" tabindex="-1"></a>msleep<span class="sc">$</span>colors[msleep<span class="sc">$</span>sleep_total <span class="sc">&lt;</span> <span class="dv">17</span>] <span class="ot">&lt;-</span><span class="st">&quot;black&quot;</span></span>
<span id="cb8-8"><a href="week-5.html#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="week-5.html#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(msleep<span class="sc">$</span>sleep_total<span class="sc">~</span>msleep<span class="sc">$</span>sleep_rem, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col=</span>msleep<span class="sc">$</span>colors, <span class="at">bty=</span><span class="st">&quot;L&quot;</span>, <span class="at">xlab=</span><span class="st">&quot;REM Sleep (hours)&quot;</span>, <span class="at">ylab=</span> <span class="st">&quot;Total Sleep (hours)&quot;</span>) </span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>In addition to scatterplots you can make histograms and boxplots in base R. The same parameter options (pch, col, ylab, xlab, etc) apply for these plots as well as scatterplots.</p>
<p>R will automatically plot a barplot if you give to the <code>plot()</code> function a continuous variable and a factor. If you have a vector stored as a character converting it to a factor via <code>as.factor</code> will make a boxplot.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="week-5.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#let&#39;s make a histogram of sleep_total and fill it with the color palette rainbow() which needs to know how many colors to use</span></span>
<span id="cb9-2"><a href="week-5.html#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="week-5.html#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(msleep<span class="sc">$</span>sleep_total, <span class="at">col=</span><span class="fu">rainbow</span>(<span class="dv">10</span>))</span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="week-5.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#let&#39;s make a boxplot of sleep_total and order making eachone a different color (how would you find out how many unique orders are in msleep?)</span></span>
<span id="cb10-2"><a href="week-5.html#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co">#using plot</span></span>
<span id="cb10-3"><a href="week-5.html#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co">#plot(msleep$sleep_total~as.factor(msleep$order), col=rainbow(19)) #this is commented out simply to avoid ploting the same plot twice</span></span>
<span id="cb10-4"><a href="week-5.html#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="week-5.html#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co">#or boxplot</span></span>
<span id="cb10-6"><a href="week-5.html#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(msleep<span class="sc">$</span>sleep_total<span class="sc">~</span><span class="fu">as.factor</span>(msleep<span class="sc">$</span>order), <span class="at">col=</span><span class="fu">rainbow</span>(<span class="dv">19</span>)) </span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-6-2.png" width="672" />
Another example looking at sleep variation across the different types of consumers (carnivore, herbivore, insectivore and omnivore):</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="week-5.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(msleep<span class="sc">$</span>sleep_total<span class="sc">~</span><span class="fu">as.factor</span>(msleep<span class="sc">$</span>vore),<span class="at">col=</span><span class="fu">rainbow</span>(<span class="dv">4</span>), <span class="at">xlab=</span><span class="st">&quot;REM Sleep (hours)&quot;</span>, <span class="at">ylab=</span> <span class="st">&quot;Total Sleep (hours)&quot;</span>)</span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
<div id="practice-problems-2.1" class="section level2" number="6.4">
<h2><span class="header-section-number">6.4</span> Practice Problems 2.1</h2>
<blockquote>
<h1 id="exercise-2.1">Exercise 2.1</h1>
<p>Read in the data using <code>data(ChickWeight)</code></p>
</blockquote>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="week-5.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Note: this dataset can also be accessed directly from the ChickWeight package in R </span></span>
<span id="cb12-2"><a href="week-5.html#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># (see ?ChickWeight)</span></span>
<span id="cb12-3"><a href="week-5.html#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;ChickWeight&quot;</span>)</span></code></pre></div>
<blockquote>
<ol style="list-style-type: decimal">
<li>First, explore the data.
How many chicks are in the dataset?
How many different diets are in the experiment?</li>
</ol>
</blockquote>
<details>
<summary>
<span style="color: red;">Solution</span>
</summary>
<p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="week-5.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(ChickWeight<span class="sc">$</span>Chick))</span></code></pre></div>
<pre><code>## [1] 50</code></pre>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="week-5.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(ChickWeight<span class="sc">$</span>Diet))</span></code></pre></div>
<pre><code>## [1] 4</code></pre>
</p>
</details>
<blockquote>
<ol start="2" style="list-style-type: decimal">
<li>To vizualize the basics of the data, plot weight versus time</li>
</ol>
</blockquote>
<details>
<summary>
<span style="color: red;">Solution</span>
</summary>
<p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="week-5.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ChickWeight<span class="sc">$</span>weight <span class="sc">~</span> ChickWeight<span class="sc">$</span>Time, </span>
<span id="cb17-2"><a href="week-5.html#cb17-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Time (days)&quot;</span>, </span>
<span id="cb17-3"><a href="week-5.html#cb17-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">&quot;Weight (gm)&quot;</span>)</span></code></pre></div>
<img src="Test_files/figure-html/unnamed-chunk-10-1.png" width="672" />
</p>
</details>
<blockquote>
<ol start="3" style="list-style-type: decimal">
<li>Plot a histogram of the weights of the chicks at the final day of the experiments (i.e. only the chicks who made it to the last day)</li>
</ol>
</blockquote>
<details>
<summary>
<span style="color: red;">Solution</span>
</summary>
<p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="week-5.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb18-2"><a href="week-5.html#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(ChickWeight<span class="sc">$</span>weight[ChickWeight<span class="sc">$</span>Time <span class="sc">==</span> <span class="fu">max</span>(ChickWeight<span class="sc">$</span>Time)], </span>
<span id="cb18-3"><a href="week-5.html#cb18-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Weight (gm)&quot;</span>, </span>
<span id="cb18-4"><a href="week-5.html#cb18-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Weights at final day of experiment&quot;</span>, </span>
<span id="cb18-5"><a href="week-5.html#cb18-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="fu">rainbow</span>(<span class="dv">10</span>))</span></code></pre></div>
<img src="Test_files/figure-html/unnamed-chunk-11-1.png" width="672" />
</p>
</details>
<blockquote>
<ol start="4" style="list-style-type: decimal">
<li>Create a boxplot where the x-axis represents the different diets and the y-axis is the weights of the chicks at the final day of the experiments</li>
</ol>
</blockquote>
<details>
<summary>
<span style="color: red;">Solution</span>
</summary>
<p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="week-5.html#cb19-1" aria-hidden="true" tabindex="-1"></a>my.new <span class="ot">=</span> ChickWeight[ChickWeight<span class="sc">$</span>Time <span class="sc">==</span> <span class="fu">max</span>(ChickWeight<span class="sc">$</span>Time), ]</span>
<span id="cb19-2"><a href="week-5.html#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(weight <span class="sc">~</span> Diet, </span>
<span id="cb19-3"><a href="week-5.html#cb19-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> my.new, </span>
<span id="cb19-4"><a href="week-5.html#cb19-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">&quot;Diet&quot;</span>, </span>
<span id="cb19-5"><a href="week-5.html#cb19-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">&quot;Weight (gm)&quot;</span>, </span>
<span id="cb19-6"><a href="week-5.html#cb19-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">&quot;Final weights given diet type&quot;</span>, </span>
<span id="cb19-7"><a href="week-5.html#cb19-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">c</span>(<span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;orange&quot;</span>, <span class="st">&quot;green&quot;</span>))</span></code></pre></div>
<img src="Test_files/figure-html/unnamed-chunk-12-1.png" width="672" />
</p>
</details>
<blockquote>
<p>Try using the package R Color Brewer to generate color palettes. Go to <a href="http://colorbrewer2.org/" class="uri">http://colorbrewer2.org/</a> to vizualize palettes. You can choose palettes that are colorblind safe, print friendly, etc.</p>
</blockquote>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="week-5.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install R Color Brewer</span></span>
<span id="cb20-2"><a href="week-5.html#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages(&quot;RColorBrewer&quot;)</span></span>
<span id="cb20-3"><a href="week-5.html#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;RColorBrewer&quot;</span>)</span></code></pre></div>
<blockquote>
<ol start="4" style="list-style-type: decimal">
<li>Define a color pallete with 10 colors and re-plot the histogram of the weights of the chicks at the final day of the experiments in these colors
Note: if histogram has n breaks and n is less than 10, it will just use first n colors. If n is greater than 10, it will reuse colors.</li>
</ol>
</blockquote>
<details>
<summary>
<span style="color: red;">Solution</span>
</summary>
<p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="week-5.html#cb21-1" aria-hidden="true" tabindex="-1"></a>my.colors <span class="ot">=</span> <span class="fu">brewer.pal</span>(<span class="dv">10</span>, <span class="st">&quot;Paired&quot;</span>)</span>
<span id="cb21-2"><a href="week-5.html#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(ChickWeight<span class="sc">$</span>weight[ChickWeight<span class="sc">$</span>Time <span class="sc">==</span> <span class="fu">max</span>(ChickWeight<span class="sc">$</span>Time)], <span class="at">xlab =</span> <span class="st">&quot;Weight (gm)&quot;</span>,<span class="at">main =</span> <span class="st">&quot;Weights at final day of experiment&quot;</span>, <span class="at">col =</span> my.colors)</span></code></pre></div>
<img src="Test_files/figure-html/unnamed-chunk-14-1.png" width="672" />
</p>
</details>
</div>
<div id="plotting-with-ggplot2" class="section level2" number="6.5">
<h2><span class="header-section-number">6.5</span> 2.2 plotting with ggplot2</h2>
<p>GGPlot is a package that allows you to make a lot of different kinds of plots and has become increasingly popular. There are also many tutorials on how to use ggplot as well as example code that could be modified to fit the data you’re interested in plotting. There is a really helpful cheatsheat (here)[<a href="https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf" class="uri">https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf</a>]</p>
<p>There is a little bit of a learning curve for ggplot as the syntax is structured differently than base R plotting. One thing that remains the same and is even more noticible in ggplot is the iterative process of building a plot, one aspect at a time.</p>
<p>Let’s demonstrate what ggplot can do with the states data set</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="week-5.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load in the data</span></span>
<span id="cb22-2"><a href="week-5.html#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(state)</span>
<span id="cb22-3"><a href="week-5.html#cb22-3" aria-hidden="true" tabindex="-1"></a>states <span class="ot">=</span> <span class="fu">as.data.frame</span>(state.x77) <span class="co"># convert data to a familiar format - data frame</span></span>
<span id="cb22-4"><a href="week-5.html#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(states) <span class="co"># let&#39;s take a look at the dataframe</span></span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    50 obs. of  8 variables:
##  $ Population: num  3615 365 2212 2110 21198 ...
##  $ Income    : num  3624 6315 4530 3378 5114 ...
##  $ Illiteracy: num  2.1 1.5 1.8 1.9 1.1 0.7 1.1 0.9 1.3 2 ...
##  $ Life Exp  : num  69 69.3 70.5 70.7 71.7 ...
##  $ Murder    : num  15.1 11.3 7.8 10.1 10.3 6.8 3.1 6.2 10.7 13.9 ...
##  $ HS Grad   : num  41.3 66.7 58.1 39.9 62.6 63.9 56 54.6 52.6 40.6 ...
##  $ Frost     : num  20 152 15 65 20 166 139 103 11 60 ...
##  $ Area      : num  50708 566432 113417 51945 156361 ...</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="week-5.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#make an initial ggplot</span></span>
<span id="cb24-2"><a href="week-5.html#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>states) </span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>We just see a grey box. In order to tell ggplot what to put in the box we use the <code>aes()</code>. The <code>aes()</code> function stands for aesthetics and will be used to specify our axes and how we want the data grouped.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="week-5.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#lets make a scatterplot of population and income</span></span>
<span id="cb25-2"><a href="week-5.html#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co">#we specify which axes we want to be x and y with aes()</span></span>
<span id="cb25-3"><a href="week-5.html#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co">#we&#39;ll then use geom_point to tell it to make a scatterplot using the data we specified in the first command</span></span>
<span id="cb25-4"><a href="week-5.html#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>states, <span class="fu">aes</span>(<span class="at">x=</span>Population, <span class="at">y=</span>Income))<span class="sc">+</span><span class="fu">geom_point</span>() </span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>There are many types of plots in ggplot that can be called with <code>geom_</code> including <code>geom_line</code>, <code>geom_boxplot</code> <code>geom_bar</code> and many others!</p>
<p>Let’s add a line to our plot that of best fit for Population ~ Income. Each time we add something to our plot we use the <code>+</code> sign. We’ll use <code>geom_smooth()</code> to draw a line with the method for <code>lm</code> which stands for linear model.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="week-5.html#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>states, <span class="fu">aes</span>(<span class="at">x=</span>Population, <span class="at">y=</span>Income))<span class="sc">+</span><span class="fu">geom_point</span>()<span class="sc">+</span><span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>) </span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>As you can already see ggplot works with many more parameters drawn in default than plotting in base R. For example, the background of our plot is grey the confidence interval of our line is drawn for us and is shaded dark grey and the line of best fit is in blue. All of these things can be modified if we wish. Many of these options can easily be changed with the <code>theme_</code> functions.</p>
<p>Let’s change to a minimal theme which removes the gray backgroun in the back of the plot. Play around with the other themes to see what they change.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="week-5.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>states, <span class="fu">aes</span>(<span class="at">x=</span>Population, <span class="at">y=</span>Income))<span class="sc">+</span><span class="fu">geom_point</span>()<span class="sc">+</span><span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>)<span class="sc">+</span><span class="fu">theme_minimal</span>() </span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Another plot example:</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="week-5.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>states, <span class="fu">aes</span>(<span class="at">x=</span>Income, <span class="at">y=</span>Illiteracy, <span class="at">color=</span>Population)) <span class="sc">+</span><span class="fu">geom_point</span>()<span class="sc">+</span><span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>)<span class="sc">+</span><span class="fu">theme_classic</span>() </span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Let’s use the <code>msleep</code> data set to explore what ggplot can do with character vectors. Make a plot of total sleep against REM sleep and then group by “vore.”</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="week-5.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># because our vore vector is a character vector we must convert it to a factor before we can use it to group or color</span></span>
<span id="cb29-2"><a href="week-5.html#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="week-5.html#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(msleep, <span class="fu">aes</span>(<span class="at">y=</span>sleep_total, <span class="at">x=</span>sleep_rem, <span class="at">group=</span><span class="fu">as.factor</span>(vore), <span class="at">color=</span><span class="fu">as.factor</span>(vore))) <span class="sc">+</span><span class="fu">geom_point</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 22 rows containing missing values (geom_point).</code></pre>
<p><img src="Test_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>That looks fine, but we may want to add axis labels and change the legend. The code below does just that and changes the theme.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="week-5.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># as we add things to the plot the line can get really long, you can hit enter after the plus sign to start a new line</span></span>
<span id="cb31-2"><a href="week-5.html#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="week-5.html#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(msleep, <span class="fu">aes</span>(<span class="at">y=</span>sleep_total, <span class="at">x=</span>sleep_rem, <span class="at">group=</span><span class="fu">as.factor</span>(vore), <span class="at">color=</span><span class="fu">as.factor</span>(vore)))<span class="sc">+</span></span>
<span id="cb31-4"><a href="week-5.html#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb31-5"><a href="week-5.html#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span> <span class="st">&quot;Total Sleep (hours)&quot;</span>, <span class="at">x=</span> <span class="st">&quot;REM sleep (hours)&quot;</span>)<span class="sc">+</span></span>
<span id="cb31-6"><a href="week-5.html#cb31-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb31-7"><a href="week-5.html#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name=</span><span class="st">&quot;Diet&quot;</span>, </span>
<span id="cb31-8"><a href="week-5.html#cb31-8" aria-hidden="true" tabindex="-1"></a>                        <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Carnivore&quot;</span>, </span>
<span id="cb31-9"><a href="week-5.html#cb31-9" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;Herbivore&quot;</span>, </span>
<span id="cb31-10"><a href="week-5.html#cb31-10" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;Insectivore&quot;</span>, </span>
<span id="cb31-11"><a href="week-5.html#cb31-11" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;Omnivore&quot;</span>, </span>
<span id="cb31-12"><a href="week-5.html#cb31-12" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">&quot;NA&quot;</span>), </span>
<span id="cb31-13"><a href="week-5.html#cb31-13" aria-hidden="true" tabindex="-1"></a>                        <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;carni&quot;</span><span class="ot">=</span><span class="st">&quot;blue&quot;</span>, </span>
<span id="cb31-14"><a href="week-5.html#cb31-14" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;herbi&quot;</span><span class="ot">=</span><span class="st">&quot;red&quot;</span>, </span>
<span id="cb31-15"><a href="week-5.html#cb31-15" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;insecti&quot;</span><span class="ot">=</span><span class="st">&quot;green&quot;</span>, </span>
<span id="cb31-16"><a href="week-5.html#cb31-16" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;omni&quot;</span><span class="ot">=</span><span class="st">&quot;brown&quot;</span>, </span>
<span id="cb31-17"><a href="week-5.html#cb31-17" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;NA&quot;</span><span class="ot">=</span><span class="st">&quot;orange&quot;</span>))</span></code></pre></div>
<pre><code>## Warning: Removed 27 rows containing missing values (geom_point).</code></pre>
<p><img src="Test_files/figure-html/unnamed-chunk-21-1.png" width="672" />
Our plot at this point is getting very clunky. You can assign what we have so far to an object and continue to add parameters without having to copy and paste the whole plot.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="week-5.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#assign to an object</span></span>
<span id="cb33-2"><a href="week-5.html#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="week-5.html#cb33-3" aria-hidden="true" tabindex="-1"></a>g<span class="ot">&lt;-</span><span class="fu">ggplot</span>(msleep, <span class="fu">aes</span>(<span class="at">y=</span>sleep_total, <span class="at">x=</span>sleep_rem, <span class="at">group=</span><span class="fu">as.factor</span>(vore), <span class="at">color=</span><span class="fu">as.factor</span>(vore)))<span class="sc">+</span></span>
<span id="cb33-4"><a href="week-5.html#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb33-5"><a href="week-5.html#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y=</span> <span class="st">&quot;Total Sleep (hours)&quot;</span>, <span class="at">x=</span> <span class="st">&quot;REM sleep (hours)&quot;</span>)<span class="sc">+</span></span>
<span id="cb33-6"><a href="week-5.html#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb33-7"><a href="week-5.html#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name=</span><span class="st">&quot;Diet&quot;</span>, </span>
<span id="cb33-8"><a href="week-5.html#cb33-8" aria-hidden="true" tabindex="-1"></a>                        <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Carnivore&quot;</span>, </span>
<span id="cb33-9"><a href="week-5.html#cb33-9" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;Herbivore&quot;</span>, </span>
<span id="cb33-10"><a href="week-5.html#cb33-10" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;Insectivore&quot;</span>, </span>
<span id="cb33-11"><a href="week-5.html#cb33-11" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;Omnivore&quot;</span>, </span>
<span id="cb33-12"><a href="week-5.html#cb33-12" aria-hidden="true" tabindex="-1"></a>                                    <span class="st">&quot;NA&quot;</span>), </span>
<span id="cb33-13"><a href="week-5.html#cb33-13" aria-hidden="true" tabindex="-1"></a>                        <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;carni&quot;</span><span class="ot">=</span><span class="st">&quot;blue&quot;</span>, </span>
<span id="cb33-14"><a href="week-5.html#cb33-14" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;herbi&quot;</span><span class="ot">=</span><span class="st">&quot;red&quot;</span>, </span>
<span id="cb33-15"><a href="week-5.html#cb33-15" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;insecti&quot;</span><span class="ot">=</span><span class="st">&quot;green&quot;</span>, </span>
<span id="cb33-16"><a href="week-5.html#cb33-16" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;omni&quot;</span><span class="ot">=</span><span class="st">&quot;brown&quot;</span>, </span>
<span id="cb33-17"><a href="week-5.html#cb33-17" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">&quot;NA&quot;</span><span class="ot">=</span><span class="st">&quot;orange&quot;</span>))</span></code></pre></div>
<p>One final example to share. I use ggplot often with data sets that have multiple character vectors and I want to see how they relate to my continuous variables. For example in the iris dataframe we may be interested in looking at the relationship between Sepal.Length and Sepal.Width for each species. You can look at all of these together with <code>facet_wrap</code> or <code>facet_grid</code>.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="week-5.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(iris, <span class="fu">aes</span>(<span class="at">y=</span>Sepal.Length, <span class="at">x=</span>Sepal.Width, <span class="at">group=</span>Species, <span class="at">color=</span>Species))<span class="sc">+</span></span>
<span id="cb34-2"><a href="week-5.html#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb34-3"><a href="week-5.html#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Species)<span class="sc">+</span></span>
<span id="cb34-4"><a href="week-5.html#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>)</span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-23-1.png" width="672" />
Finally in ggplot we may be interested in seeing the mean values plotted with error bars for several groups. You can use the function <code>stat_summary</code> to find the mean and error around that mean for the given grouping.</p>
<p>Here’s a plot looking at the mean chickweight by diet.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="week-5.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ChickWeight, <span class="fu">aes</span>(<span class="at">x=</span>Time, <span class="at">y=</span>weight, <span class="at">group=</span>Diet, <span class="at">color=</span>Diet))<span class="sc">+</span></span>
<span id="cb35-2"><a href="week-5.html#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y=</span>mean, <span class="at">geom=</span><span class="st">&quot;point&quot;</span>, <span class="at">size=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb35-3"><a href="week-5.html#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y=</span>mean, <span class="at">geom=</span><span class="st">&quot;line&quot;</span>, <span class="at">size=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb35-4"><a href="week-5.html#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">&quot;errorbar&quot;</span>, </span>
<span id="cb35-5"><a href="week-5.html#cb35-5" aria-hidden="true" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">width=</span><span class="fl">0.1</span>), <span class="at">size=</span><span class="fl">0.5</span>)</span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
</div>
<div id="practice-problems-2.2" class="section level2" number="6.6">
<h2><span class="header-section-number">6.6</span> Practice Problems 2.2</h2>
<blockquote>
<h1 id="exercise-2.2-plotting-in-ggplot">Exercise 2.2 Plotting in ggplot</h1>
</blockquote>
<blockquote>
<ol style="list-style-type: decimal">
<li>Add best fit lines to our msleep plot for each order.</li>
</ol>
</blockquote>
<details>
<summary>
<span style="color: red;">Solution</span>
</summary>
<p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="week-5.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we can just use the geom_smooth command from above and ggplot takes care of the rest!</span></span>
<span id="cb36-2"><a href="week-5.html#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The code below will only work if you stored your plot in object g.</span></span>
<span id="cb36-3"><a href="week-5.html#cb36-3" aria-hidden="true" tabindex="-1"></a>g<span class="sc">+</span><span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 22 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 27 rows containing missing values (geom_point).</code></pre>
<img src="Test_files/figure-html/unnamed-chunk-25-1.png" width="672" />
</p>
</details>
<blockquote>
<ol start="2" style="list-style-type: decimal">
<li>In the msleep data, make a boxplot of sleep_total against vore. Make sure vore is a factor. Color the boxplots by vore (remember how we had to color the boxplots in base R) it is similar in ggplot.</li>
</ol>
</blockquote>
<details>
<summary>
<span style="color: red;">Solution</span>
</summary>
<p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="week-5.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(msleep, <span class="fu">aes</span>(<span class="at">y=</span>sleep_total, <span class="at">x=</span><span class="fu">as.factor</span>(vore), <span class="at">fill=</span><span class="fu">as.factor</span>(vore)))<span class="sc">+</span><span class="fu">geom_boxplot</span>()</span></code></pre></div>
<img src="Test_files/figure-html/unnamed-chunk-26-1.png" width="672" />
</p>
</details>
<blockquote>
<ol start="3" style="list-style-type: decimal">
<li>Load a new dataframe <code>midwest</code>(run data(midwest)) and plot a scatterplot of area against popdensity grouped and color by state. Do a facet grid by state.</li>
</ol>
</blockquote>
<details>
<summary>
<span style="color: red;">Solution</span>
</summary>
<p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="week-5.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(midwest, <span class="fu">aes</span>(<span class="at">y=</span>area, <span class="at">x=</span>popdensity, <span class="at">col=</span><span class="fu">as.factor</span>(state)))<span class="sc">+</span><span class="fu">geom_point</span>()<span class="sc">+</span><span class="fu">facet_grid</span>(<span class="sc">~</span>state)</span></code></pre></div>
<img src="Test_files/figure-html/unnamed-chunk-27-1.png" width="672" />
</p>
</details>
<blockquote>
<ol start="4" style="list-style-type: decimal">
<li>In the midwest dataframe make a scatterplot of the popdensity by poptotal of only IL (this requires you to subset your data for illinois).</li>
</ol>
</blockquote>
<details>
<summary>
<span style="color: red;">Solution</span>
</summary>
<p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="week-5.html#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#we can subset our data first and store the subset in a new dataframe</span></span>
<span id="cb41-2"><a href="week-5.html#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="week-5.html#cb41-3" aria-hidden="true" tabindex="-1"></a>il<span class="ot">&lt;-</span>midwest[midwest<span class="sc">$</span>state <span class="sc">==</span> <span class="st">&quot;IL&quot;</span>,]</span>
<span id="cb41-4"><a href="week-5.html#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="week-5.html#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(il, <span class="fu">aes</span>(<span class="at">x=</span>popdensity, <span class="at">y=</span>poptotal))<span class="sc">+</span><span class="fu">geom_point</span>() </span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
</p>
</details>
<blockquote>
<ol start="5" style="list-style-type: decimal">
<li>In the midwest dataframe plot the mean and standard error for popdensity for each state. Color this plot in your favorite palette.</li>
</ol>
</blockquote>
<details>
<summary>
<span style="color: red;">Solution</span>
</summary>
<p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="week-5.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(midwest, <span class="fu">aes</span>(<span class="at">x=</span>state, <span class="at">y=</span>popdensity, <span class="at">color=</span>state))<span class="sc">+</span></span>
<span id="cb42-2"><a href="week-5.html#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y=</span>mean, <span class="at">geom=</span><span class="st">&quot;point&quot;</span>, <span class="at">size=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb42-3"><a href="week-5.html#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.y=</span>mean, <span class="at">geom=</span><span class="st">&quot;line&quot;</span>, <span class="at">size=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb42-4"><a href="week-5.html#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_se, <span class="at">geom =</span> <span class="st">&quot;errorbar&quot;</span>, </span>
<span id="cb42-5"><a href="week-5.html#cb42-5" aria-hidden="true" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">width=</span><span class="fl">0.1</span>), <span class="at">size=</span><span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb42-6"><a href="week-5.html#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()<span class="sc">+</span></span>
<span id="cb42-7"><a href="week-5.html#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values=</span><span class="fu">rainbow</span>(<span class="dv">5</span>))</span></code></pre></div>
<pre><code>## geom_path: Each group consists of only one observation. Do you need to
## adjust the group aesthetic?</code></pre>
<img src="Test_files/figure-html/unnamed-chunk-29-1.png" width="672" />
</p>
</details>
</div>
<div id="for-loops-and-the-apply-family-of-functions" class="section level2" number="6.7">
<h2><span class="header-section-number">6.7</span> For loops and the apply family of functions</h2>
<p>A few useful commands: function(), is.na, which, var, length, for(){ },
points, print, paste, plot, unique, sample</p>
<p>for loops:
In many languages, the best way to repeat a calculation is to use a for-loop:
For example, we could square each number 1 to 10</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="week-5.html#cb44-1" aria-hidden="true" tabindex="-1"></a>squares <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">NA</span>, <span class="dv">10</span>) <span class="co"># use rep to create a vector length 10 of NAs to store the result</span></span>
<span id="cb44-2"><a href="week-5.html#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>) { <span class="co"># for loop</span></span>
<span id="cb44-3"><a href="week-5.html#cb44-3" aria-hidden="true" tabindex="-1"></a>  squares[i] <span class="ot">=</span> i<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb44-4"><a href="week-5.html#cb44-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb44-5"><a href="week-5.html#cb44-5" aria-hidden="true" tabindex="-1"></a>squares</span></code></pre></div>
<pre><code>##  [1]   1   4   9  16  25  36  49  64  81 100</code></pre>
<p>An alternative to for-loops in R is using the ‘apply’ family, while for-loops apply a function to one item at a time and then go on to the next one, “apply” applies functions to every item at once</p>
</div>
<div id="apply-family" class="section level2" number="6.8">
<h2><span class="header-section-number">6.8</span> apply family</h2>
<div id="sapply" class="section level3" number="6.8.1">
<h3><span class="header-section-number">6.8.1</span> sapply</h3>
<p>There are several apply functions that vary in the output the return and vary somewhat in the input they require. We’ll go over <strong>sapply</strong> “simplifying” apply which returns a vector, first.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="week-5.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co">#?sapply </span></span>
<span id="cb46-2"><a href="week-5.html#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="co"># syntax: sapply(X = object_to_repeat_over, FUN = function_to_repeat)</span></span>
<span id="cb46-3"><a href="week-5.html#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="week-5.html#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="co"># simple example of sapply over a vector</span></span>
<span id="cb46-5"><a href="week-5.html#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="co"># we can use an in-line function definition</span></span>
<span id="cb46-6"><a href="week-5.html#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="cf">function</span>(x)  x<span class="sc">^</span><span class="dv">2</span>)</span></code></pre></div>
<pre><code>##  [1]   1   4   9  16  25  36  49  64  81 100</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="week-5.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># equivalently, we can define our own functions separately for sapply</span></span>
<span id="cb48-2"><a href="week-5.html#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="co"># e.g. a function that calculates the area of a circle radius r, pi*r^2</span></span>
<span id="cb48-3"><a href="week-5.html#cb48-3" aria-hidden="true" tabindex="-1"></a>areaCircle <span class="ot">=</span> <span class="cf">function</span>(r){</span>
<span id="cb48-4"><a href="week-5.html#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(pi <span class="sc">*</span> r<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb48-5"><a href="week-5.html#cb48-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb48-6"><a href="week-5.html#cb48-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-7"><a href="week-5.html#cb48-7" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, areaCircle)</span></code></pre></div>
<pre><code>##  [1]   3.141593  12.566371  28.274334  50.265482  78.539816 113.097336
##  [7] 153.938040 201.061930 254.469005 314.159265</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="week-5.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># in R, we can also just use short-hand for simple vector calculations:</span></span>
<span id="cb50-2"><a href="week-5.html#cb50-2" aria-hidden="true" tabindex="-1"></a>pi<span class="sc">*</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<pre><code>##  [1]   3.141593  12.566371  28.274334  50.265482  78.539816 113.097336
##  [7] 153.938040 201.061930 254.469005 314.159265</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="week-5.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># but unlike the short-hand, sapply can also iterate over elements in a list</span></span>
<span id="cb52-2"><a href="week-5.html#cb52-2" aria-hidden="true" tabindex="-1"></a>listy <span class="ot">=</span> <span class="fu">list</span>(<span class="at">a =</span> <span class="cn">TRUE</span>, <span class="at">b =</span> <span class="fu">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;b&quot;</span>, <span class="st">&quot;c&quot;</span>), <span class="at">c =</span> <span class="dv">10</span><span class="sc">:</span><span class="dv">100</span>)</span>
<span id="cb52-3"><a href="week-5.html#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(listy) <span class="co"># look at the structure of &#39;listy&#39;</span></span></code></pre></div>
<pre><code>## List of 3
##  $ a: logi TRUE
##  $ b: chr [1:3] &quot;a&quot; &quot;b&quot; &quot;c&quot;
##  $ c: int [1:91] 10 11 12 13 14 15 16 17 18 19 ...</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="week-5.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(listy) <span class="co"># look at the length of &#39;listy&#39;</span></span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="week-5.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use sapply to return a vector for length of each object within the list</span></span>
<span id="cb56-2"><a href="week-5.html#cb56-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-3"><a href="week-5.html#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(listy, <span class="at">FUN =</span> length) </span></code></pre></div>
<pre><code>##  a  b  c 
##  1  3 91</code></pre>
<p>You can also use sapply to create plots! For example, use sapply to plot these 4 dataframes at once:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="week-5.html#cb58-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">x1 =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">y1 =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span>
<span id="cb58-2"><a href="week-5.html#cb58-2" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">x2 =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">y2 =</span> <span class="sc">-</span><span class="dv">1</span><span class="sc">:-</span><span class="dv">10</span>)</span>
<span id="cb58-3"><a href="week-5.html#cb58-3" aria-hidden="true" tabindex="-1"></a>df3 <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">x3 =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">y3 =</span> <span class="dv">10</span><span class="sc">:</span><span class="dv">1</span>)</span>
<span id="cb58-4"><a href="week-5.html#cb58-4" aria-hidden="true" tabindex="-1"></a>df4 <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">x4 =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">y4 =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span>
<span id="cb58-5"><a href="week-5.html#cb58-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-6"><a href="week-5.html#cb58-6" aria-hidden="true" tabindex="-1"></a>my_list <span class="ot">=</span> <span class="fu">list</span>(df1, df2, df3, df4) <span class="co"># put 4 data frames together in a list</span></span>
<span id="cb58-7"><a href="week-5.html#cb58-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-8"><a href="week-5.html#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>)) <span class="co"># set up frame for 4 plots</span></span>
<span id="cb58-9"><a href="week-5.html#cb58-9" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(my_list, plot) <span class="co"># plot my_list with sapply</span></span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-32-1.png" width="672" /></p>
<pre><code>## [[1]]
## NULL
## 
## [[2]]
## NULL
## 
## [[3]]
## NULL
## 
## [[4]]
## NULL</code></pre>
</div>
<div id="apply" class="section level3" number="6.8.2">
<h3><span class="header-section-number">6.8.2</span> apply</h3>
<p>The apply function is highly useful for applying a function to rows or columns of a dataframe or matrix.
Example syntax for the dataframe or matrix X:
<code>apply(X = over this object, MARGIN 1 for rows or 2 for columns,FUN = apply this function)</code></p>
<p>You can also use apply on a dataframe we worked with earlier the states data to plot each column against Population</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="week-5.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load in the data</span></span>
<span id="cb60-2"><a href="week-5.html#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(state)</span>
<span id="cb60-3"><a href="week-5.html#cb60-3" aria-hidden="true" tabindex="-1"></a>states <span class="ot">=</span> <span class="fu">as.data.frame</span>(state.x77) <span class="co"># convert data to a familiar format - data frame</span></span>
<span id="cb60-4"><a href="week-5.html#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(states) <span class="co"># let&#39;s take a look at the dataframe</span></span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    50 obs. of  8 variables:
##  $ Population: num  3615 365 2212 2110 21198 ...
##  $ Income    : num  3624 6315 4530 3378 5114 ...
##  $ Illiteracy: num  2.1 1.5 1.8 1.9 1.1 0.7 1.1 0.9 1.3 2 ...
##  $ Life Exp  : num  69 69.3 70.5 70.7 71.7 ...
##  $ Murder    : num  15.1 11.3 7.8 10.1 10.3 6.8 3.1 6.2 10.7 13.9 ...
##  $ HS Grad   : num  41.3 66.7 58.1 39.9 62.6 63.9 56 54.6 52.6 40.6 ...
##  $ Frost     : num  20 152 15 65 20 166 139 103 11 60 ...
##  $ Area      : num  50708 566432 113417 51945 156361 ...</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="week-5.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the mean for each column</span></span>
<span id="cb62-2"><a href="week-5.html#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(states, <span class="dv">2</span>, mean)</span></code></pre></div>
<pre><code>## Population     Income Illiteracy   Life Exp     Murder    HS Grad 
##  4246.4200  4435.8000     1.1700    70.8786     7.3780    53.1080 
##      Frost       Area 
##   104.4600 70735.8800</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="week-5.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># note you could get this with colMeans() or summary(), along with the min and max and other values, but there may be instances where you only want the mean</span></span>
<span id="cb64-2"><a href="week-5.html#cb64-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-3"><a href="week-5.html#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="co"># you could also plot each column against Population in ggplot</span></span>
<span id="cb64-4"><a href="week-5.html#cb64-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-5"><a href="week-5.html#cb64-5" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(states, <span class="dv">2</span>, <span class="at">FUN =</span> <span class="cf">function</span>(i) <span class="fu">ggplot</span>(states, <span class="fu">aes</span>(<span class="at">x=</span>Population, <span class="at">y =</span> i))<span class="sc">+</span><span class="fu">geom_point</span>()<span class="sc">+</span><span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>)<span class="sc">+</span><span class="fu">theme_classic</span>())</span></code></pre></div>
<pre><code>## $Population</code></pre>
<p><img src="Test_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<pre><code>## 
## $Income</code></pre>
<p><img src="Test_files/figure-html/unnamed-chunk-33-2.png" width="672" /></p>
<pre><code>## 
## $Illiteracy</code></pre>
<p><img src="Test_files/figure-html/unnamed-chunk-33-3.png" width="672" /></p>
<pre><code>## 
## $`Life Exp`</code></pre>
<p><img src="Test_files/figure-html/unnamed-chunk-33-4.png" width="672" /></p>
<pre><code>## 
## $Murder</code></pre>
<p><img src="Test_files/figure-html/unnamed-chunk-33-5.png" width="672" /></p>
<pre><code>## 
## $`HS Grad`</code></pre>
<p><img src="Test_files/figure-html/unnamed-chunk-33-6.png" width="672" /></p>
<pre><code>## 
## $Frost</code></pre>
<p><img src="Test_files/figure-html/unnamed-chunk-33-7.png" width="672" /></p>
<pre><code>## 
## $Area</code></pre>
<p><img src="Test_files/figure-html/unnamed-chunk-33-8.png" width="672" /></p>
<p>We can do the same things across all rows. But if you want to plot all the rows as we did the columns above, I suggest you do that with a smaller dataset than the states dataframe.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="week-5.html#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co">#calculate the sum across each row in states</span></span>
<span id="cb73-2"><a href="week-5.html#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(states, <span class="dv">1</span>, sum)</span></code></pre></div>
<pre><code>##        Alabama         Alaska        Arizona       Arkansas     California 
##       58094.55      573412.81      120312.25       57620.56      182838.71 
##       Colorado    Connecticut       Delaware        Florida        Georgia 
##      111500.46       13581.68        7604.76       67328.26       67280.04 
##         Hawaii          Idaho       Illinois        Indiana           Iowa 
##       12399.60       87872.27       72312.94       46121.58       63704.36 
##         Kansas       Kentucky      Louisiana          Maine       Maryland 
##       88987.58       46964.80       52419.96       35961.49       19544.92 
##  Massachusetts       Michigan      Minnesota    Mississippi       Missouri 
##       18632.73       70939.43       88178.46       52908.99       78253.59 
##        Montana       Nebraska         Nevada  New Hampshire     New Jersey 
##      150970.36       82809.40      115962.23       14426.83       20335.73 
##     New Mexico       New York North Carolina   North Dakota           Ohio 
##      126414.42       71027.55       58314.61       75308.28       56527.22 
##       Oklahoma         Oregon   Pennsylvania   Rhode Island South Carolina 
##       75692.52      103308.93       61528.73        6787.00       36860.66 
##   South Dakota      Tennessee          Texas           Utah        Vermont 
##       81102.58       49516.61      278726.70       87603.30       13948.84 
##       Virginia     Washington  West Virginia      Wisconsin        Wyoming 
##       49675.78       75165.12       29705.18       63800.68      102458.69</code></pre>
</div>
<div id="lapply-list-apply" class="section level3" number="6.8.3">
<h3><span class="header-section-number">6.8.3</span> lapply – “list” apply</h3>
<p>We’ll just show a quick example of lapply. It works in the same way as sapply, but returns a list instead of a vector.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="week-5.html#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="cf">function</span>(x)  x<span class="sc">^</span><span class="dv">2</span>) <span class="co"># lapply returns list</span></span></code></pre></div>
<pre><code>## [[1]]
## [1] 1
## 
## [[2]]
## [1] 4
## 
## [[3]]
## [1] 9
## 
## [[4]]
## [1] 16
## 
## [[5]]
## [1] 25
## 
## [[6]]
## [1] 36
## 
## [[7]]
## [1] 49
## 
## [[8]]
## [1] 64
## 
## [[9]]
## [1] 81
## 
## [[10]]
## [1] 100</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="week-5.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="cf">function</span>(x)  x<span class="sc">^</span><span class="dv">2</span>, <span class="at">simplify =</span> <span class="cn">FALSE</span>) <span class="co"># same as an lapply</span></span></code></pre></div>
<pre><code>## [[1]]
## [1] 1
## 
## [[2]]
## [1] 4
## 
## [[3]]
## [1] 9
## 
## [[4]]
## [1] 16
## 
## [[5]]
## [1] 25
## 
## [[6]]
## [1] 36
## 
## [[7]]
## [1] 49
## 
## [[8]]
## [1] 64
## 
## [[9]]
## [1] 81
## 
## [[10]]
## [1] 100</code></pre>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="week-5.html#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="cf">function</span>(x)  x<span class="sc">^</span><span class="dv">2</span>) <span class="co"># default is simplify = TRUE which retuns a vector</span></span></code></pre></div>
<pre><code>##  [1]   1   4   9  16  25  36  49  64  81 100</code></pre>
</div>
<div id="tapply---per-type-apply" class="section level3" number="6.8.4">
<h3><span class="header-section-number">6.8.4</span> tapply - “per Type” apply</h3>
<p>The tapply function is one of my favorites because it is a really great way to sumarize data that has multiple categorical variables that can be</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="week-5.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load state data again, you can skip this if you already have it loaded</span></span>
<span id="cb81-2"><a href="week-5.html#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(state)</span>
<span id="cb81-3"><a href="week-5.html#cb81-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-4"><a href="week-5.html#cb81-4" aria-hidden="true" tabindex="-1"></a>states <span class="ot">=</span> <span class="fu">as.data.frame</span>(state.x77) <span class="co"># convert data to a familiar format - data frame</span></span>
<span id="cb81-5"><a href="week-5.html#cb81-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(states) <span class="co"># let&#39;s take a look at the dataframe</span></span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    50 obs. of  8 variables:
##  $ Population: num  3615 365 2212 2110 21198 ...
##  $ Income    : num  3624 6315 4530 3378 5114 ...
##  $ Illiteracy: num  2.1 1.5 1.8 1.9 1.1 0.7 1.1 0.9 1.3 2 ...
##  $ Life Exp  : num  69 69.3 70.5 70.7 71.7 ...
##  $ Murder    : num  15.1 11.3 7.8 10.1 10.3 6.8 3.1 6.2 10.7 13.9 ...
##  $ HS Grad   : num  41.3 66.7 58.1 39.9 62.6 63.9 56 54.6 52.6 40.6 ...
##  $ Frost     : num  20 152 15 65 20 166 139 103 11 60 ...
##  $ Area      : num  50708 566432 113417 51945 156361 ...</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="week-5.html#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="co"># example syntax --- tapply(variable of interest, grouping variable, function)</span></span>
<span id="cb83-2"><a href="week-5.html#cb83-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-3"><a href="week-5.html#cb83-3" aria-hidden="true" tabindex="-1"></a><span class="co"># for each US region in our dataset, finds the mean of Frost for states in that region</span></span>
<span id="cb83-4"><a href="week-5.html#cb83-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(states<span class="sc">$</span>Frost, state.region, mean) <span class="co"># state.region contains the region information for each state</span></span></code></pre></div>
<pre><code>##     Northeast         South North Central          West 
##      132.7778       64.6250      138.8333      102.1538</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="week-5.html#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># you can nest apply statements! Let&#39;s find the region average for all the variables in the states dataset</span></span>
<span id="cb85-2"><a href="week-5.html#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(states,</span>
<span id="cb85-3"><a href="week-5.html#cb85-3" aria-hidden="true" tabindex="-1"></a>      <span class="dv">2</span>, <span class="co"># apply over columns of my_states</span></span>
<span id="cb85-4"><a href="week-5.html#cb85-4" aria-hidden="true" tabindex="-1"></a>      <span class="cf">function</span>(x) <span class="fu">tapply</span>(x, state.region, mean)) <span class="co"># each column = variable of interest for tapply</span></span></code></pre></div>
<pre><code>##               Population   Income Illiteracy Life Exp    Murder  HS Grad
## Northeast       5495.111 4570.222   1.000000 71.26444  4.722222 53.96667
## South           4208.125 4011.938   1.737500 69.70625 10.581250 44.34375
## North Central   4803.000 4611.083   0.700000 71.76667  5.275000 54.51667
## West            2915.308 4702.615   1.023077 71.23462  7.215385 62.00000
##                  Frost      Area
## Northeast     132.7778  18141.00
## South          64.6250  54605.12
## North Central 138.8333  62652.00
## West          102.1538 134463.00</code></pre>
</div>
</div>
<div id="exercise-2.3-apply-and-tapply" class="section level2" number="6.9">
<h2><span class="header-section-number">6.9</span> Exercise 2.3 apply and tapply</h2>
<blockquote>
<h1 id="exercise-2.3">Exercise 2.3</h1>
</blockquote>
<p>A few useful commands: function(){ }, apply(), tapply(), hist(), dim(), prod(), sd()</p>
<blockquote>
<ol style="list-style-type: decimal">
<li>what is the average population, income, and area of all 50 states ins the <code>states</code> dataset</li>
</ol>
</blockquote>
<details>
<summary>
<span style="color: red;">Solution</span>
</summary>
<p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="week-5.html#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load state data</span></span>
<span id="cb87-2"><a href="week-5.html#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="co">#?state</span></span>
<span id="cb87-3"><a href="week-5.html#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(state)</span>
<span id="cb87-4"><a href="week-5.html#cb87-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-5"><a href="week-5.html#cb87-5" aria-hidden="true" tabindex="-1"></a><span class="co"># this data is stored in a slightly different way than other datasets we&#39;ve used so far</span></span>
<span id="cb87-6"><a href="week-5.html#cb87-6" aria-hidden="true" tabindex="-1"></a>states <span class="ot">=</span> <span class="fu">as.data.frame</span>(state.x77) <span class="co"># run this line of code to avoid later confusion</span></span>
<span id="cb87-7"><a href="week-5.html#cb87-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-8"><a href="week-5.html#cb87-8" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(states,<span class="dv">2</span>,mean)</span></code></pre></div>
<pre><code>## Population     Income Illiteracy   Life Exp     Murder    HS Grad 
##  4246.4200  4435.8000     1.1700    70.8786     7.3780    53.1080 
##      Frost       Area 
##   104.4600 70735.8800</code></pre>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="week-5.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co">#or an alternative that will get you only the columns requested</span></span>
<span id="cb89-2"><a href="week-5.html#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colMeans</span>(states[,<span class="fu">c</span>(<span class="st">&quot;Population&quot;</span>, <span class="st">&quot;Income&quot;</span>, <span class="st">&quot;Area&quot;</span>)])</span></code></pre></div>
<pre><code>## Population     Income       Area 
##    4246.42    4435.80   70735.88</code></pre>
</p>
</details>
<blockquote>
<ol start="2" style="list-style-type: decimal">
<li>what is the average area of the states from different regions of the country?
Hint: use the object state.region in your environment</li>
</ol>
</blockquote>
<details>
<summary>
<span style="color: red;">Solution</span>
</summary>
<p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="week-5.html#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(states<span class="sc">$</span>Area, state.region, mean)</span></code></pre></div>
<pre><code>##     Northeast         South North Central          West 
##      18141.00      54605.12      62652.00     134463.00</code></pre>
</p>
</details>
<blockquote>
<ol start="3" style="list-style-type: decimal">
<li>Plot a histogram for each column in the states data (Population, Income, Illiteracy etc.)</li>
</ol>
</blockquote>
<details>
<summary>
<span style="color: red;">Solution</span>
</summary>
<p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="week-5.html#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co">#how many columns do we have? </span></span>
<span id="cb93-2"><a href="week-5.html#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(states)</span></code></pre></div>
<pre><code>## [1] 50  8</code></pre>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="week-5.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>)) <span class="co"># make your plot window show 2 rows and 2 columns at once</span></span>
<span id="cb95-2"><a href="week-5.html#cb95-2" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(states, <span class="dv">2</span>, hist)</span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-39-1.png" width="672" /><img src="Test_files/figure-html/unnamed-chunk-39-2.png" width="672" /></p>
<pre><code>## $Population
## $breaks
## [1]     0  5000 10000 15000 20000 25000
## 
## $counts
## [1] 38  6  4  1  1
## 
## $density
## [1] 0.000152 0.000024 0.000016 0.000004 0.000004
## 
## $mids
## [1]  2500  7500 12500 17500 22500
## 
## $xname
## [1] &quot;newX[, i]&quot;
## 
## $equidist
## [1] TRUE
## 
## attr(,&quot;class&quot;)
## [1] &quot;histogram&quot;
## 
## $Income
## $breaks
## [1] 3000 3500 4000 4500 5000 5500 6000 6500
## 
## $counts
## [1]  2 11 11 18  7  0  1
## 
## $density
## [1] 0.00008 0.00044 0.00044 0.00072 0.00028 0.00000 0.00004
## 
## $mids
## [1] 3250 3750 4250 4750 5250 5750 6250
## 
## $xname
## [1] &quot;newX[, i]&quot;
## 
## $equidist
## [1] TRUE
## 
## attr(,&quot;class&quot;)
## [1] &quot;histogram&quot;
## 
## $Illiteracy
## $breaks
## [1] 0.5 1.0 1.5 2.0 2.5 3.0
## 
## $counts
## [1] 26 11  7  5  1
## 
## $density
## [1] 1.04 0.44 0.28 0.20 0.04
## 
## $mids
## [1] 0.75 1.25 1.75 2.25 2.75
## 
## $xname
## [1] &quot;newX[, i]&quot;
## 
## $equidist
## [1] TRUE
## 
## attr(,&quot;class&quot;)
## [1] &quot;histogram&quot;
## 
## $`Life Exp`
## $breaks
## [1] 67 68 69 70 71 72 73 74
## 
## $counts
## [1]  1  3  5 21  8 11  1
## 
## $density
## [1] 0.02 0.06 0.10 0.42 0.16 0.22 0.02
## 
## $mids
## [1] 67.5 68.5 69.5 70.5 71.5 72.5 73.5
## 
## $xname
## [1] &quot;newX[, i]&quot;
## 
## $equidist
## [1] TRUE
## 
## attr(,&quot;class&quot;)
## [1] &quot;histogram&quot;
## 
## $Murder
## $breaks
## [1]  0  2  4  6  8 10 12 14 16
## 
## $counts
## [1]  2  9  8 10  4 12  4  1
## 
## $density
## [1] 0.02 0.09 0.08 0.10 0.04 0.12 0.04 0.01
## 
## $mids
## [1]  1  3  5  7  9 11 13 15
## 
## $xname
## [1] &quot;newX[, i]&quot;
## 
## $equidist
## [1] TRUE
## 
## attr(,&quot;class&quot;)
## [1] &quot;histogram&quot;
## 
## $`HS Grad`
## $breaks
## [1] 35 40 45 50 55 60 65 70
## 
## $counts
## [1]  4  6  4 15 13  5  3
## 
## $density
## [1] 0.016 0.024 0.016 0.060 0.052 0.020 0.012
## 
## $mids
## [1] 37.5 42.5 47.5 52.5 57.5 62.5 67.5
## 
## $xname
## [1] &quot;newX[, i]&quot;
## 
## $equidist
## [1] TRUE
## 
## attr(,&quot;class&quot;)
## [1] &quot;histogram&quot;
## 
## $Frost
## $breaks
##  [1]   0  20  40  60  80 100 120 140 160 180 200
## 
## $counts
##  [1]  6  2  3  4  5  7 11  4  6  2
## 
## $density
##  [1] 0.006 0.002 0.003 0.004 0.005 0.007 0.011 0.004 0.006 0.002
## 
## $mids
##  [1]  10  30  50  70  90 110 130 150 170 190
## 
## $xname
## [1] &quot;newX[, i]&quot;
## 
## $equidist
## [1] TRUE
## 
## attr(,&quot;class&quot;)
## [1] &quot;histogram&quot;
## 
## $Area
## $breaks
## [1] 0e+00 1e+05 2e+05 3e+05 4e+05 5e+05 6e+05
## 
## $counts
## [1] 42  6  1  0  0  1
## 
## $density
## [1] 8.4e-06 1.2e-06 2.0e-07 0.0e+00 0.0e+00 2.0e-07
## 
## $mids
## [1]  50000 150000 250000 350000 450000 550000
## 
## $xname
## [1] &quot;newX[, i]&quot;
## 
## $equidist
## [1] TRUE
## 
## attr(,&quot;class&quot;)
## [1] &quot;histogram&quot;</code></pre>
</p>
</details>
<blockquote>
<ol start="4" style="list-style-type: decimal">
<li>let’s assume that we don’t want to live in a state with high illiteracy, high murder, and many freezing days; also assume that each of these factors contribute equally to our opinion (Illiteracy * Murder * Frost) = undesirable
What 10 states should we avoid? # hint use prod(); and maybe order()</li>
</ol>
</blockquote>
<details>
<summary>
<span style="color: red;">Solution</span>
</summary>
<p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="week-5.html#cb97-1" aria-hidden="true" tabindex="-1"></a>livability <span class="ot">&lt;-</span> <span class="fu">apply</span>(states[,<span class="fu">c</span>(<span class="st">&quot;Illiteracy&quot;</span>, <span class="st">&quot;Murder&quot;</span>, <span class="st">&quot;Frost&quot;</span>)], <span class="dv">1</span>, prod) <span class="co"># subset to variables of interest</span></span>
<span id="cb97-2"><a href="week-5.html#cb97-2" aria-hidden="true" tabindex="-1"></a>livability[<span class="fu">order</span>(livability, <span class="at">decreasing =</span> T)][<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>] <span class="co"># top ten least livable states</span></span></code></pre></div>
<pre><code>##         Alaska     New Mexico South Carolina        Georgia       Kentucky 
##        2576.40        2560.80        1734.20        1668.00        1611.20 
## North Carolina    Mississippi      Tennessee       New York       Michigan 
##        1598.40        1500.00        1309.00        1251.32        1248.75</code></pre>
</p>
</details>
<blockquote>
<ol start="5" style="list-style-type: decimal">
<li>use sapply() to plot a histogram of the data below 4 times, in 4 different colors.
For extra style, title the plot by it’s color, e.g. the red plot is titled “red”</li>
</ol>
</blockquote>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="week-5.html#cb99-1" aria-hidden="true" tabindex="-1"></a>data_to_plot <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>)</span>
<span id="cb99-2"><a href="week-5.html#cb99-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb99-3"><a href="week-5.html#cb99-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))<span class="co"># run this line to set your plot to make 4 plots in total (2rows, 2columns)</span></span></code></pre></div>
<details>
<summary>
<span style="color: red;">Solution</span>
</summary>
<p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="week-5.html#cb100-1" aria-hidden="true" tabindex="-1"></a>data_to_plot <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>)</span>
<span id="cb100-2"><a href="week-5.html#cb100-2" aria-hidden="true" tabindex="-1"></a>my_colors <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;deeppink&quot;</span>, <span class="st">&quot;red&quot;</span>, <span class="st">&quot;blue&quot;</span>, <span class="st">&quot;darkgreen&quot;</span>)</span>
<span id="cb100-3"><a href="week-5.html#cb100-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>)) <span class="co"># extra styling, plots in a 2x2 grid</span></span>
<span id="cb100-4"><a href="week-5.html#cb100-4" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(my_colors, <span class="at">FUN =</span> <span class="cf">function</span>(i) <span class="fu">hist</span>(data_to_plot, <span class="at">main =</span> i, <span class="at">col =</span> i))</span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<pre><code>##          deeppink       red            blue           darkgreen     
## breaks   Integer,6      Integer,6      Integer,6      Integer,6     
## counts   Integer,5      Integer,5      Integer,5      Integer,5     
## density  Numeric,5      Numeric,5      Numeric,5      Numeric,5     
## mids     Numeric,5      Numeric,5      Numeric,5      Numeric,5     
## xname    &quot;data_to_plot&quot; &quot;data_to_plot&quot; &quot;data_to_plot&quot; &quot;data_to_plot&quot;
## equidist TRUE           TRUE           TRUE           TRUE</code></pre>
</p>
</details>
<blockquote>
<ol start="6" style="list-style-type: decimal">
<li>Standardize all the variables in the states dataset and save your answer to a new dataframe, states_standardized
Hint: to standardize a variable, you subtract the mean and divide by the standard deviation (sd)</li>
</ol>
</blockquote>
<details>
<summary>
<span style="color: red;">Solution</span>
</summary>
<p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="week-5.html#cb102-1" aria-hidden="true" tabindex="-1"></a>states_standardized <span class="ot">=</span> <span class="fu">apply</span>(states, <span class="dv">2</span>, <span class="cf">function</span>(x) (x<span class="sc">-</span><span class="fu">mean</span>(x))<span class="sc">/</span><span class="fu">sd</span>(x))</span>
<span id="cb102-2"><a href="week-5.html#cb102-2" aria-hidden="true" tabindex="-1"></a><span class="co"># original:</span></span>
<span id="cb102-3"><a href="week-5.html#cb102-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(states)</span></code></pre></div>
<pre><code>##            Population Income Illiteracy Life Exp Murder HS Grad Frost
## Alabama          3615   3624        2.1    69.05   15.1    41.3    20
## Alaska            365   6315        1.5    69.31   11.3    66.7   152
## Arizona          2212   4530        1.8    70.55    7.8    58.1    15
## Arkansas         2110   3378        1.9    70.66   10.1    39.9    65
## California      21198   5114        1.1    71.71   10.3    62.6    20
## Colorado         2541   4884        0.7    72.06    6.8    63.9   166
##              Area
## Alabama     50708
## Alaska     566432
## Arizona    113417
## Arkansas    51945
## California 156361
## Colorado   103766</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="week-5.html#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="co"># standardized</span></span>
<span id="cb104-2"><a href="week-5.html#cb104-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(states_standardized)</span></code></pre></div>
<pre><code>##            Population     Income Illiteracy   Life Exp     Murder
## Alabama    -0.1414316 -1.3211387   1.525758 -1.3621937  2.0918101
## Alaska     -0.8693980  3.0582456   0.541398 -1.1685098  1.0624293
## Arizona    -0.4556891  0.1533029   1.033578 -0.2447866  0.1143154
## Arkansas   -0.4785360 -1.7214837   1.197638 -0.1628435  0.7373617
## California  3.7969790  1.1037155  -0.114842  0.6193415  0.7915396
## Colorado   -0.3819965  0.7294092  -0.771082  0.8800698 -0.1565742
##               HS Grad      Frost       Area
## Alabama    -1.4619293 -1.6248292 -0.2347183
## Alaska      1.6828035  0.9145676  5.8093497
## Arizona     0.6180514 -1.7210185  0.5002047
## Arkansas   -1.6352611 -0.7591257 -0.2202212
## California  1.1751891 -1.6248292  1.0034903
## Colorado    1.3361400  1.1838976  0.3870991</code></pre>
</p>
</details>
<blockquote>
<ol start="7" style="list-style-type: decimal">
<li>Create a histogram again for each variable in the states data, but this time label each histogram with the variable names when you plot
Hint: instead of using apply to iterate over the columns themselves, you can often iterate over the column names with sapply</li>
</ol>
</blockquote>
<details>
<summary>
<span style="color: red;">Solution</span>
</summary>
<p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="week-5.html#cb106-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb106-2"><a href="week-5.html#cb106-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(<span class="fu">colnames</span>(states), <span class="cf">function</span>(x)<span class="fu">hist</span>(states[ , x],<span class="at">main =</span> x, <span class="at">xlab =</span> x,<span class="at">col =</span> <span class="st">&quot;darkblue&quot;</span>))</span></code></pre></div>
<p><img src="Test_files/figure-html/unnamed-chunk-44-1.png" width="672" /><img src="Test_files/figure-html/unnamed-chunk-44-2.png" width="672" /></p>
<pre><code>##          Population    Income        Illiteracy    Life Exp     
## breaks   Numeric,6     Integer,8     Numeric,6     Integer,8    
## counts   Integer,5     Integer,7     Integer,5     Integer,7    
## density  Numeric,5     Numeric,7     Numeric,5     Numeric,7    
## mids     Numeric,5     Numeric,7     Numeric,5     Numeric,7    
## xname    &quot;states[, x]&quot; &quot;states[, x]&quot; &quot;states[, x]&quot; &quot;states[, x]&quot;
## equidist TRUE          TRUE          TRUE          TRUE         
##          Murder        HS Grad       Frost         Area         
## breaks   Numeric,9     Integer,8     Numeric,11    Numeric,7    
## counts   Integer,8     Integer,7     Integer,10    Integer,6    
## density  Numeric,8     Numeric,7     Numeric,10    Numeric,6    
## mids     Numeric,8     Numeric,7     Numeric,10    Numeric,6    
## xname    &quot;states[, x]&quot; &quot;states[, x]&quot; &quot;states[, x]&quot; &quot;states[, x]&quot;
## equidist TRUE          TRUE          TRUE          TRUE</code></pre>
</p>
</details>
</div>
<div id="creature-of-the-week-4" class="section level2" number="6.10">
<h2><span class="header-section-number">6.10</span> Creature of the Week!</h2>
<div class="figure">
<img src="figs/creatures/wobbegong.jpg" alt="" />
<p class="caption">Juvenile Banded Wobbegong, photo © Grey McNeil</p>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="week-4.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="week-6-pca.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Test.pdf", "Test.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
